In [ ]:
#importing libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
# Load  data from Local drive
from google.colab import files
uploaded = files.upload()

Saving house-prices.csv to house-prices.csv


In [ ]:
dataset = pd.read_csv('house-prices.csv')
print(dataset)


     Home     Price    SqFt  Bedrooms  Bathrooms  Offers Brick Neighborhood
0       1  114300.0  1790.0         2          2       2    No         East
1       2  114200.0  2030.0         4          2       3    No         East
2       3  114800.0  1740.0         3          2       1    No         East
3       4   94700.0  1980.0         3          2       3    No         East
4       5  119800.0  2130.0         3          3       3    No         East
..    ...       ...     ...       ...        ...     ...   ...          ...
123   124       NaN  1900.0         3          3       3   Yes         East
124   125  147900.0  2160.0         4          3       3   Yes         East
125   126  113500.0  2070.0         2          2       2    No        North
126   127  149900.0  2020.0         3          3       1    No         West
127   128  124600.0  2250.0         3          3       4    No        North

[128 rows x 8 columns]


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
dataset ['Price'] = dataset['Price'].fillna(dataset['Price'].median())
dataset ['SqFt'] = dataset['SqFt'].fillna(dataset['SqFt'].median())

In [ ]:
# Extracting dependent and independent variables:
# Extracting independent variable:
X = dataset.iloc[:,2:8].values
# Extracting dependent variable:
y = dataset.iloc[:, 1].values
print(X)
print(y)

[[1790.0 2 2 2 'No' 'East']
 [2030.0 4 2 3 'No' 'East']
 [1740.0 3 2 1 'No' 'East']
 [1980.0 3 2 3 'No' 'East']
 [2130.0 3 3 3 'No' 'East']
 [1780.0 3 2 2 'No' 'North']
 [1830.0 3 3 3 'Yes' 'West']
 [2160.0 4 2 2 'No' 'West']
 [2110.0 4 2 3 'No' 'East']
 [1730.0 3 3 3 'No' 'East']
 [2030.0 3 2 3 'Yes' 'East']
 [1870.0 2 2 2 'Yes' 'East']
 [1910.0 3 2 4 'No' 'North']
 [2150.0 3 3 5 'Yes' 'North']
 [2590.0 4 3 4 'No' 'West']
 [1780.0 4 2 1 'No' 'West']
 [2190.0 3 3 4 'Yes' 'East']
 [2000.0 3 3 4 'No' 'North']
 [1700.0 2 2 1 'Yes' 'East']
 [1920.0 3 3 2 'Yes' 'West']
 [1790.0 3 2 3 'No' 'East']
 [2000.0 3 2 4 'No' 'North']
 [1690.0 3 2 3 'No' 'North']
 [1820.0 3 2 3 'Yes' 'North']
 [2210.0 4 3 2 'Yes' 'East']
 [2290.0 4 3 3 'No' 'North']
 [2000.0 4 2 3 'No' 'West']
 [1700.0 3 2 2 'No' 'East']
 [1600.0 2 2 3 'No' 'North']
 [2000.0 4 3 1 'Yes' 'West']
 [2250.0 4 3 3 'Yes' 'West']
 [1930.0 2 2 2 'Yes' 'North']
 [2250.0 3 3 3 'Yes' 'East']
 [2280.0 5 3 4 'Yes' 'East']
 [2000.0 2 2 3 'No' 'Nor

In [ ]:
details = pd.DataFrame(X, columns =['SqFt','Price','Bedrooms','Bathrooms','Offers','Brick'])
details.isnull().sum()

SqFt         0
Price        0
Bedrooms     0
Bathrooms    0
Offers       0
Brick        0
dtype: int64

In [ ]:
# Encoding Categorical data:
# Encoding the Independent Variable
from sklearn.preprocessing import LabelEncoder
labelencoder_X = LabelEncoder()
X[:, 4] = labelencoder_X.fit_transform(X[:, 4])
X[:, 5] = labelencoder_X.fit_transform(X[:, 5])

In [ ]:
print(X)

[[1790.0 2 2 2 0 0]
 [2030.0 4 2 3 0 0]
 [1740.0 3 2 1 0 0]
 [1980.0 3 2 3 0 0]
 [2130.0 3 3 3 0 0]
 [1780.0 3 2 2 0 1]
 [1830.0 3 3 3 1 2]
 [2160.0 4 2 2 0 2]
 [2110.0 4 2 3 0 0]
 [1730.0 3 3 3 0 0]
 [2030.0 3 2 3 1 0]
 [1870.0 2 2 2 1 0]
 [1910.0 3 2 4 0 1]
 [2150.0 3 3 5 1 1]
 [2590.0 4 3 4 0 2]
 [1780.0 4 2 1 0 2]
 [2190.0 3 3 4 1 0]
 [2000.0 3 3 4 0 1]
 [1700.0 2 2 1 1 0]
 [1920.0 3 3 2 1 2]
 [1790.0 3 2 3 0 0]
 [2000.0 3 2 4 0 1]
 [1690.0 3 2 3 0 1]
 [1820.0 3 2 3 1 1]
 [2210.0 4 3 2 1 0]
 [2290.0 4 3 3 0 1]
 [2000.0 4 2 3 0 2]
 [1700.0 3 2 2 0 0]
 [1600.0 2 2 3 0 1]
 [2000.0 4 3 1 1 2]
 [2250.0 4 3 3 1 2]
 [1930.0 2 2 2 1 1]
 [2250.0 3 3 3 1 0]
 [2280.0 5 3 4 1 0]
 [2000.0 2 2 3 0 1]
 [2080.0 3 3 3 0 1]
 [1880.0 2 2 2 0 1]
 [2420.0 4 3 4 0 2]
 [1720.0 3 2 1 0 2]
 [1740.0 3 2 2 0 1]
 [2000.0 2 2 1 0 0]
 [1840.0 4 3 2 0 2]
 [1990.0 2 2 3 0 0]
 [1920.0 3 2 1 1 0]
 [1940.0 3 3 2 1 2]
 [1810.0 3 2 3 0 0]
 [2000.0 2 3 2 0 1]
 [2050.0 3 2 6 0 1]
 [1980.0 2 2 2 0 0]
 [1700.0 3 2 3 1 1]


In [ ]:
dataset.describe()

Home          Price         SqFt    Bedrooms   Bathrooms  \
count  128.000000     128.000000   128.000000  128.000000  128.000000   
mean    64.500000  130216.406250  2002.656250    3.023438    2.445312   
std     37.094474   26554.373803   205.524045    0.725951    0.514492   
min      1.000000   69100.000000  1450.000000    2.000000    2.000000   
25%     32.750000  112125.000000  1897.500000    3.000000    2.000000   
50%     64.500000  125700.000000  2000.000000    3.000000    2.000000   
75%     96.250000  148250.000000  2140.000000    3.000000    3.000000   
max    128.000000  211200.000000  2590.000000    5.000000    4.000000   

           Offers  
count  128.000000  
mean     2.578125  
std      1.069324  
min      1.000000  
25%      2.000000  
50%      3.000000  
75%      3.000000  
max      6.000000

In [ ]:
# Splitting the Dataset into the Training set and Test set

# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [ ]:
print(X_train)

[[1950.0 3 3 3 1 2]
 [2130.0 3 2 3 0 1]
 [2050.0 3 2 6 0 1]
 [1790.0 2 2 2 0 0]
 [1910.0 3 2 4 0 1]
 [1990.0 2 2 3 0 0]
 [2020.0 3 3 1 0 2]
 [2210.0 4 3 2 1 0]
 [2040.0 4 3 3 0 0]
 [1740.0 2 2 2 0 1]
 [2000.0 2 2 4 0 1]
 [1780.0 4 2 1 0 2]
 [2000.0 4 3 3 1 2]
 [1690.0 3 2 3 0 1]
 [1940.0 3 3 2 1 2]
 [1450.0 2 2 1 1 1]
 [1970.0 2 2 1 1 2]
 [2250.0 4 3 3 1 2]
 [2220.0 4 3 2 0 2]
 [1930.0 3 3 3 0 0]
 [1730.0 3 3 3 0 0]
 [2280.0 5 3 4 1 0]
 [2210.0 3 3 4 0 1]
 [2290.0 4 3 3 0 1]
 [1900.0 3 3 3 0 1]
 [1600.0 2 2 3 0 1]
 [2000.0 2 2 1 1 0]
 [2150.0 3 2 2 0 0]
 [2000.0 3 2 3 0 1]
 [1780.0 3 2 2 0 1]
 [2140.0 3 2 4 0 1]
 [2040.0 3 3 2 0 0]
 [1740.0 3 2 2 0 1]
 [1700.0 3 2 3 1 1]
 [2080.0 3 3 3 0 1]
 [2190.0 3 3 4 1 0]
 [2060.0 2 2 1 1 0]
 [2000.0 2 2 3 0 1]
 [2250.0 4 3 2 1 2]
 [2160.0 4 2 2 0 2]
 [1920.0 3 2 1 1 0]
 [1930.0 3 2 2 0 2]
 [1940.0 2 2 2 1 0]
 [2000.0 3 3 3 1 0]
 [2110.0 4 2 3 0 0]
 [2150.0 3 3 5 1 1]
 [2080.0 3 3 2 0 0]
 [1980.0 3 2 3 0 0]
 [2000.0 3 3 4 0 1]
 [1720.0 3 2 1 0 2]


In [ ]:
print(y_train)

[166700. 121300.  90300. 114300. 125700. 105600. 149900. 156400. 151900.
 125700.  97800. 145800. 176500.  91700. 166500. 111100. 152500. 182000.
 161300. 105600. 104000. 139600. 126200. 149300. 102500.  69100. 126800.
 116500. 130800. 114600.  93600. 125700. 108200. 125700. 117100. 125700.
 144800. 117800. 188300. 150700. 154000. 129800. 123600. 117000. 119200.
 126300. 157100.  94700.  83600. 125700. 107300. 103200. 151600. 147700.
 111600. 109700.  81300. 151100. 117800. 129800. 125700. 100900. 147900.
 143600. 123100. 133600. 125700. 143100. 115900. 127700. 108700. 152300.
 106900. 135000. 110400. 155400. 120500. 134000. 147000. 188000. 124500.
 114200. 117400. 113800. 114800. 106100. 211200. 171000. 172500. 199500.
 144200. 102700. 164800. 124600. 116200. 180900. 157600. 108500. 176800.
 125700.  91100. 125700.]


In [ ]:

print(y_test)

[125700. 106600. 167200. 112300. 145500. 140900. 165600.  82300. 184300.
 137000. 160600.  99300. 130300. 119800. 133300. 115700. 117500. 125700.
 113500.  90500. 111400. 132500. 150200. 123000. 146900. 103200.]


In [ ]:
print(X_test)

[[1720.0 2 2 2 1 0]
 [2000.0 2 2 1 0 0]
 [1920.0 3 3 2 1 2]
 [1930.0 2 2 2 1 1]
 [2000.0 3 2 1 0 2]
 [2190.0 3 2 3 1 0]
 [2080.0 4 3 3 0 2]
 [1910.0 3 2 4 0 0]
 [2140.0 4 3 2 1 2]
 [2000.0 4 2 3 0 2]
 [2150.0 4 3 3 1 2]
 [1700.0 3 2 2 0 0]
 [1860.0 3 2 2 0 2]
 [2130.0 3 3 3 0 0]
 [2440.0 3 3 3 0 0]
 [2000.0 3 2 3 1 1]
 [1880.0 2 2 2 0 1]
 [2190.0 3 3 4 1 0]
 [2070.0 2 2 2 0 1]
 [1520.0 2 2 3 0 1]
 [1700.0 2 2 1 1 0]
 [2030.0 3 2 3 1 0]
 [1950.0 3 2 3 1 1]
 [1870.0 2 2 2 1 0]
 [2530.0 4 3 4 0 2]
 [1810.0 3 2 3 0 0]]


In [ ]:

details = pd.DataFrame(X, columns =['SqFt','Price','Bedrooms','Bathrooms','Offers','Brick'])
details.isnull().sum()

SqFt         0
Price        0
Bedrooms     0
Bathrooms    0
Offers       0
Brick        0
dtype: int64

In [ ]:
# Fitting Simple Linear Regression to the Training set
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression()

In [ ]:
y_pred = regressor.predict(X_test)
print(y_pred)


[113820.95211208 120122.47342255 158749.18471214 136162.16884809
 146476.02765249 138440.37807101 144819.52727809  91821.31439401
 178387.40164496 133363.67944076 169130.94960548  99062.73679605
 128321.03744702 121432.15243681 139822.46464653 137052.15969771
 113037.21827616 135300.65096926 124308.69995309  81831.03876057
 122484.16827383 128948.60402729 134085.98030904 122719.49027807
 161665.45385885  95738.6435339 ]


In [ ]:
print("Regressor slope:  %2.f  "%( regressor.coef_[0]))
print("Regressor intercept:%2.f  "% regressor.intercept_)

Regressor slope:  59  
Regressor intercept:-15269  


In [ ]:
SqFt= 1790
Bedrooms = 2
Bathrooms = 2
Offers = 2
Brick = 1
Neighborhood = 2
print("Price for given SqFt is :     %.2f"    %(regressor.predict([[SqFt,Bedrooms,Bathrooms,Offers,Brick,Neighborhood]])))

Price for given SqFt is :     137740.13


In [ ]:
from sklearn import metrics
print("MAE %2.f" %(metrics.mean_absolute_error(y_test,y_pred)))

MAE 8771


In [ ]:
from sklearn import metrics
print("RMSE %2.f" %(np.sqrt(metrics.mean_absolute_error(y_test,y_pred))))

RMSE 94


In [ ]:
print('Train Score: %f' %(regressor.score(X_train, y_train)))
print('Test Score: %f' % (regressor.score(X_test, y_test)) )
print("Underfitting")

Train Score: 0.829635
Test Score: 0.795444
Underfitting


In [ ]:
import pickle

# Save the trained model as a pickle string.
saved_model = pickle.dumps(regressor)

# Load the pickled model
saved_model = pickle.loads(saved_model)

# Use the loaded pickled model to make predictions
saved_model.predict(X_test)

array([113820.95211208, 120122.47342255, 158749.18471214, 136162.16884809,
       146476.02765249, 138440.37807101, 144819.52727809,  91821.31439401,
       178387.40164496, 133363.67944076, 169130.94960548,  99062.73679605,
       128321.03744702, 121432.15243681, 139822.46464653, 137052.15969771,
       113037.21827616, 135300.65096926, 124308.69995309,  81831.03876057,
       122484.16827383, 128948.60402729, 134085.98030904, 122719.49027807,
       161665.45385885,  95738.6435339 ])

In [ ]:
import joblib
filename = '/content/drive/My Drive/linear.sav'
joblib.dump(regressor, filename)

# some time later...

# load the model from disk
loaded_model = joblib.load(filename)
result = loaded_model.score(X_test, y_test)
print(result)

0.7954436576128349


In [ ]:
import pickle
print("[INFO] Saving model...")
# Save the trained model as a pickle string.
saved_model=pickle.dump(regressor,open('/content/drive/My Drive/linearregressionm.pkl', 'wb'))
# Saving model to disk

[INFO] Saving model...


In [ ]:
# Load the pickled model
import pickle
model = pickle.load(open('/content/drive/My Drive/linearregressionm.pkl','rb'))
# Use the loaded pickled model to make predictions
model.predict(X_test)

array([113820.95211208, 120122.47342255, 158749.18471214, 136162.16884809,
       146476.02765249, 138440.37807101, 144819.52727809,  91821.31439401,
       178387.40164496, 133363.67944076, 169130.94960548,  99062.73679605,
       128321.03744702, 121432.15243681, 139822.46464653, 137052.15969771,
       113037.21827616, 135300.65096926, 124308.69995309,  81831.03876057,
       122484.16827383, 128948.60402729, 134085.98030904, 122719.49027807,
       161665.45385885,  95738.6435339 ])

In [ ]:
!pip install flask-ngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
# Mounting Google Drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
%mkdir templates -p

In [ ]:
%%writefile templates/index.html
<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
<title>Machine Learning Lab Experiment Deployment</title>
<meta charset="UTF-8">
<link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
<style><!DOCTYPE html>

h1 {text-align: center;}
h2 {text-align: center;}
h3 {text-align: center;}
p {text-align: center;}
div {text-align: center;}
</style>
</head>

<body>


<div class="" style="background-color:blue;" >
<div class="clearfix">

<div class="col-md-12">
<center><p style="font-size:40px;color:white;margin-top:10px;">Poornima Institute of Engineering & Technology</p></center>
<center><p style="font-size:30px;color:white;margin-top:10px;">Department of Computer Engineering</p></center>
<center><p style="font-size:25px;color:white;margin-top:10px;">Machine Learning Experiment Deployment</p></center>
</div>
</div>
</div>

<div class="login">
<h2 >Regression Analysis to predict the price by the inputes for a Area</h2>
<h4>Developed by Mohammed Umar Tanwar</h4>
<!-- Main Input For Receiving Query to our ML -->
<form action="{{ url_for('predict')}}"method="get">
<div class="form-floating mb-3">

<input type="number" class="form-control" id=" SqFt" name="SqFt" step="any" min="0" max="10000000000" placeholder="0" required="required">
<label for="floatingInput">Enter Sqft of Area</label>
</div>
<br>

<div class="form-floating mb-3">
<input type="number" class="form-control" id="bedrooms" name="bedrooms" step="any" min="0" max="10" placeholder="0" required="required">
<label for="floatingInput">Enter no. of Bedrooms</label>
</div>
<br>

<div class="form-floating mb-3">
<input type="number" class="form-control" id="Bathrooms" name="Bathrooms" step="any" min="0" max="10" placeholder="0" required="required">
<label for="floatingInput">Enter number of bathrooms</label>
</div>
<br>

<div class="form-floating mb-3">
<input type="number" class="form-control" id="Offers" name="Offers" step="any" min="0" max="10" placeholder="0" required="required">
<label for="floatingInput">Enter no. of offers</label>
</div>
<br>

<div class="form-floating mb-3">
<input type="number" class="form-control" id="bricks" name="bricks" step="any" min="0" max="10" placeholder="0" required="required">
<label for="floatingInput">Enter the brick is available or not</label>
</div>
<br>

<div class="form-floating mb-3">
<input type="number" class="form-control" id="Neighborhood" name="Neighborhood" step="any" min="0" max="10" placeholder="0" required="required">
<label for="floatingInput">Enter the Neighborhood</label>
</div>
<br>

<br>
<button type="submit" class="btn btn-primary btn-block btn-large">Predict Price for Given Requirements</button>
</form>
<br>
<br>
{{ prediction_text }}

</div>

<div class="" style="background-color:blue;" >
<div class="clearfix">

<div class="col-md-12">
 <center><p style="font-size:25px;color:white;margin-top:20px;">Machine Learning  Experiment </p></center>
</div>
</div>
</div>
</body>
</html>


Overwriting templates/index.html


In [ ]:
!pip install pyngrok

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:
!ngrok authtoken 2CebPKTfQzem3M2a2RRLmeYtmat_5JzFSFD2RpqB3WbcGCAzJ

Authtoken saved to configuration file: /root/.ngrok2/ngrok.yml


In [ ]:
import numpy as np
from flask import Flask, request, jsonify, render_template
from flask_ngrok import run_with_ngrok
import pickle


app = Flask(__name__)
model = pickle.load(open('/content/drive/My Drive/linearregressionm.pkl','rb'))
run_with_ngrok(app)

@app.route('/')
def home():

    return render_template("index.html")

@app.route('/predict',methods=['GET'])
def predict():


    '''
    For rendering results on HTML GUI
    '''

    r1 = float(request.args.get('SqFt'))
    r2 = float(request.args.get('bedrooms'))
    r3 = float(request.args.get('Bathrooms'))
    r4 = float(request.args.get('Offers'))
    r5 = float(request.args.get('bricks'))
    r6 = float(request.args.get('Neighborhood'))

    result=np.array([r1,r2,r3,r4,r5,r6]).reshape(1,-1)
    prediction = model.predict(result)



    return render_template('index.html', prediction_text='Regression Model  has predicted Price for given requirements is : {}'.format(prediction))


app.run()

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   Use a production WSGI server instead.
 * Debug mode: off


 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)


 * Running on http://009a-35-237-181-23.ngrok.io
 * Traffic stats available on http://127.0.0.1:4040


127.0.0.1 - - [30/Jul/2022 15:42:02] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [30/Jul/2022 15:42:03] "GET /favicon.ico HTTP/1.1" 404 -
